name: Confirm Review Thread Comments

# on:
#   schedule:
#     - cron: '5 0 * * *'

jobs:
  confirm:
    name: Confirm review thread comments
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt config.json
      run: ./.github/scripts/decrypt.sh
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run confirm_comments.py
      run: python scripts/confirm_comments.py
  update:
    needs: confirm
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push updated data JSON
      run: |
        git add ./json/data.json
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Update data"
        git push