name: Confirm Review Thread Comments

# on:
#   schedule:
#     - cron: '0 * * * *'

jobs:
  confirm:
    name: Confirm review thread comments
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt config.json
      run: ./.github/scripts/decrypt.sh
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run confirm_comments.py
      run: python scripts/confirm_comments.py